FROM node:18.16.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

RUN npm install

COPY . .

EXPOSE 4444

CMD ["npm", "run", "dev"]